@startuml
skinparam style strictuml
skinparam linetype ortho
hide empty members

package "Budget" #f0fff0 {
  class Client {
    + id: uri
    + name: string
  }

  class Budget {
    + client: id
    + AdCampaignBundle: id
    + amount: float
  }

  class AdCampaignBundle {
    + id: uri
    + name: string
  }
}

package "Goal" #ffe4e1 {
    abstract class Goal
    class EndDateGoal {
      + end_date: datetime
    }
    class BudgetGoal {
      budget: MonetaryValue
      useAdCampaignBundleBudget: boolean
    }
    class ImpressionGoal {
      + impressions: integer
    }
    Goal <|-- EndDateGoal
    Goal <|-- BudgetGoal
    Goal <|-- ImpressionGoal
}

package "Billing" #f0ffff {
    class Billing {
      + type: BillingType
      + fee: MonetaryValue
    }

    class BillableEvent {
      + timestamp: datetime
      + amount: MonetaryValue
      + type: BillableEventType
    }

    enum BillingType {
      {static} CPM
      {static} CPCV
      {static} CPUM
      {static} FLAT_FEE
      {static} SETUP_FEE
    }

    enum BillableEventType {
      {static} IMPRESSION
      {static} CLICK
      {static} CAMPAIGN_LAUNCHED
      {static} CAMPAIGN_COMPLETE
      {static} SETUP
      {static} FUNNEL_UNLOCK
      {static} FUNNEL_REDEMPTION
    }
}

package "Ad Format" #87ceeb {
    abstract class AdFormat {
      + id: uri
    }

    class MediaAd {
      + creative: blob
    }
    note bottom of MediaAd: e.g. Engagements,\nBanners
    AdFormat <|-- MediaAd
    class PremiumPlacementAd {
      + sponsored_content: uri
    }
    note bottom of PremiumPlacementAd: e.g. Sponsored Offers,\nFeatured Retailers
    AdFormat <|-- PremiumPlacementAd
}

package "Tracking and behavior" #fa8072 {
    class FunnelTracking {
      + uri: uri
      + type: FunnelTrackingType
    }

    abstract class ClickThrough {

    }
    class ClickThroughSearchTerm {
      query: string
    }
    class ClickThroughOfferList {
      uri: uri[]
    }
    ClickThrough <|-- ClickThroughSearchTerm
    ClickThrough <|-- ClickThroughOfferList

    class PerformanceTracking {
      + customer: uri
      + timestamp: datetime
    }

    enum FunnelTrackingType {
      {static} UNLOCK
      {static} REDEMPTION
    }
}

package "Permission & History" #ff69b4 {
    class ChangeHistory {
      + timestamp: datetime
      + change: string
      + oldValue: string
      + newValue: value
    }

    class Permissions {
      + action: ActionType
      + user: uri
      + permission: Permission
    }
}

class AdCampaign {
  + id: uri
  + segments: int[]
    startTime: DateTime
  + passback: boolean
  + paceFactor: float
}

class Placement {
  + uri: uri
  position: int
}

enum CampaignStatus {
  {static} DRAFT
  {static} SCHEDULED
  {static} CANCELLED
  {static} LAUNCHED
  {static} STOPPED
  {static} COMPLETED
}

/' Relations '/
AdCampaignBundle "1" -right- "1..*" Budget
Budget "1" -right- "1..*" Client

BillingType "1" -up- "1" Billing
Billing "1" -right- "0..*" BillableEvent
BillableEvent "1" -down- "1" BillableEventType

FunnelTracking "0..*" -down- "1" FunnelTrackingType

AdCampaign "1..*" -left- AdCampaignBundle
AdCampaign "1" -- "1" AdFormat
AdCampaign "0..*" -up- "1" CampaignStatus
AdCampaign "0..*" -up- "1" Placement
AdCampaign "0..*" -- "0..2" Goal
AdCampaign "1" -- "0..*" ClickThrough
AdCampaign "0..*"  -- "1" Billing
AdCampaign "1" -- "0..*" FunnelTracking
AdCampaign "1" -- "0..*" PerformanceTracking
AdCampaign "1" -up- "0..*" ChangeHistory
AdCampaign "1" -up- "0..*" Permissions

@enduml
